version: '2'
services:
    highcliff-app:
        image: highcliff
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://highcliff-postgresql:5432/highcliff
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    highcliff-postgresql:
        extends:
            file: postgresql.yml
            service: highcliff-postgresql
